version: '3.9'

services:
  resume_parser:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./employee_docs:/app/employee_docs
      - ./jd_docs:/app/jd_docs
    container_name: resume_parser_container
